#!/bin/bash
#=============================================================================
# My files are too big. But if I strip out all the comments then my submission
# will make it under the 1MB limit.
#
# The alternative would probably be to clean up my code but that's a lot more
# work than writing a short bash script. :-)
#=============================================================================

TEMP_DIR='entry'

# clear out a temp directory to put files in
[ -d "$TEMP_DIR" ] || mkdir "$TEMP_DIR"
rm "./${TEMP_DIR}/"* 2>/dev/null

for file in `ls *.{cpp,h,cc}`; do
	'./strip-comments.sed' "$file" > "./${TEMP_DIR}/${file}_1"
	sed '/^[ \t]*$/d' "./${TEMP_DIR}/${file}_1" > "./${TEMP_DIR}/${file}"
	rm "./${TEMP_DIR}/${file}_1"
done

zip `date +%Y%m%d%H%M%S`.zip "${TEMP_DIR}/"*

# remove the temp dir
rm "./${TEMP_DIR}/"*
rmdir "${TEMP_DIR}"
